### ISSUE TITLE
Remove direct reference for sending mails.

### ISSUE THREAD

**Issue by MrTech12** [MrTech12/TimeMate#5]
# Reason
The logic for sending mails is currently, tightly integrated into the Business class. This needs to be separated, in case another mailprovider needs to be used in the future. 

## Tasks

- [ ] Create an interface for sending mails.
- [ ] Create an implementation for sending mails using Gmail.
- [ ] Reference the interface in the Business class that makes use of sending mails.

## Helpful links
t.b.d.
